Blog/urls.py
from django.urls import path
from .views import blog, categoria

urlpatterns = [
    path('',blog, name="Blog"),
    path('categoria/<int:categoria_id>/', categoria, name="categoria")
]

Carro/urls.py
from django.urls import path
from .views import agregrar_producto,eliminar_producto,restar_producto,limpiar_carro

app_name="carro"

urlpatterns=[
    path("agregar/<int:producto_id>/",agregrar_producto,name="agregar"),
    path("eliminar/<int:producto_id>/",eliminar_producto,name="eliminar"),
    path("restar/<int:producto_id>/",restar_producto,name="restar"),
    path("limpiar/",limpiar_carro,name="limpiar"),
]

ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('Servicios.urls',)),
    path('blog/', include('Blog.urls',)),
    path('contacto/', include('Contacto.urls',)),
    path('tienda/', include('Tienda.urls',)),
    path('carro/', include('Carro.urls',)),
    path('autenticacion/', include('Autenticacion.urls',)),
    #path('pedidos/', include('Pedidos.urls',)),
    path('',include('ProyectoWebApp.urls',)),
]

Tienda/urls.py
from django.urls import path
from .views import tienda


urlpatterns = [
    path('',tienda, name="Tienda"),
]

Tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name="categoriaProd"
        verbose_name_plural="categoriasProd"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='tienda',default='tienda/default.png')
    precio=models.FloatField()
    disponibilidad=models.BooleanField()
    descripcion=models.TextField(null=True,blank=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name="producto"
        verbose_name_plural="productos"

    






Carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from Tienda.models import Producto

# Create your views here.

def agregrar_producto(request,producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar_producto(producto=producto)
    return redirect("Tienda")

def eliminar_producto(request,producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar_producto(producto=producto)
    return redirect("Tienda")

def restar_producto(request,producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("Tienda")

def limpiar_carro(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("Tienda")



Tienda/views.py
from django.shortcuts import render, HttpResponse
from .models import Producto

# Create your views here.

def tienda(request):
    productos=Producto.objects.all()

    return render(request, "tienda/tienda.html",{'productos':productos})


def buscar(request):
    if request.GET["prod"]:
        producto=request.GET["prod"]
        if len(producto)>20:
            mensaje="Texto de busqueda demasiado largo"
        else:
            productos=Producto.objects.filter(nombre__icontains=producto) #__icontains es como si fuera un like en SQL
            return render(request, "tienda/resultados_busq_prod.html", {"articulos":productos, "query":producto})
    else:
        mensaje="No has introducido nada"
    return HttpResponse(mensaje)


Tienda/templates/carro/widget.html


<table class="table table-bordered" style="color: black; background-color: white; margin-left: 20px; margin-top: 10px; width: 350px;">
    <head>
        <tr>
            <th  colspan="3" class="text-center">           
                    <div class="contenedor-icono-carro">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                    </svg> CARRO COMPRA
                    </div>  
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </head>
    <body>
        {% if request.session.carro.items %}
            {% for key,value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a></br>
                        $ {{value.precio}}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin Productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </body>
    <tfoot>
        <tr>
            <td colspan="3">
                <p style="color: black; text-align: center;font-weight: bold">Total: $ {{importe_total_carro}}</p>
            </td>
        </tr>
        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" style="color: black; text-align: center;font-weight: bold">
                <a href="a" class="btn btn-success">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-check-fill" viewBox="0 0 16 16">
                        <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm-1.646-7.646-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708.708z"/>
                    </svg> &nbsp; Comprar
                </a>
            </td>
        </tr>
        {% endif %}
    </tfoot>
</table>